# Generated by Django 5.1.5 on 2025-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profile',
            field=models.ImageField(default='profile\\icon_profile.png', upload_to='photos de profile'),
        ),
    ]
