# Generated by Django 5.1.5 on 2025-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publicatio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
